---
- hosts: all
  become: true
  #vars_files:
    #-vars.yml
  vars:
    mysql_root_password: admin
    mysql_user_password: 1234
  
  tasks:
    - name: install required dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python3-pip
        #- python-pymysql

    - name: install mysql pip
      ansible.builtin.pip:
        name: pymysql
        state: present 
    
    - name: add mysql repository key
      apt_key:
        keyserver: pgp.mit.edu
        id: 5072E1F5
        state: present
    
    - name: add official Mysql 5.7 ubuntu 
      apt_repository:
        repo: "deb http://repo.mysql.com/apt/ubuntu bionic mysql-5.7"
        state: present

    - name: Install Mysql dependecies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-common
        - mysql-server
        - mysql-client

    - name: Start Mysql
      service:
        name: mysql
        state: started
        enabled: yes

    - name: copy initial mysql client config file
      copy:
        src: .my.cnf
        dest: /root/.my.cnf

    - name: update mysql root password 
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - 127.0.0.1
        - ::1
        - localhost
        - "{{ ansible_host }}"

    - name: create root myconfi with root password creden
      template:
        src: .my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: 0600

    - name: create the mysql database
      mysql_db: 
        name: "test"
        state: present

    - name: create database user
      mysql_user:
        name: db_user
        password: "{{ mysql_user_password }}"
        priv: '*.*:ALL'
        state: present    